/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: tndz.c                                                *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: D:\LZG\acd.txt                                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fonttndz;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_0030[ 16] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_0031[ 16] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ____X___,
  __XXX___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  __XXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_0032[ 16] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X____X_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_0033[ 16] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ___XX___,
  _____X__,
  ______X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_0039[ 16] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  __XXX_X_,
  ______X_,
  ______X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_0044[ 16] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___,
  ________,
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_4E8C[ 32] = { /* code 4E8C */
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XXXXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_5357[ 32] = { /* code 5357 */
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  _X__X___,__X__X__,
  _X___X__,_X___X__,
  _X__XXXX,XXX__X__,
  _X_____X,_____X__,
  _X_____X,_____X__,
  _X_XXXXX,XXXX_X__,
  _X_____X,_____X__,
  _X_____X,_____X__,
  _X_____X,___X_X__,
  _X______,____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_53F6[ 32] = { /* code 53F6 */
  ________,__X_____,
  ________,__X_____,
  _XXXX___,__X_____,
  _X__X___,__X_____,
  _X__X___,__X_____,
  _X__X___,__X_____,
  _X__X_XX,XXXXXXX_,
  _X__X___,__X_____,
  _X__X___,__X_____,
  _X__X___,__X_____,
  _XXXX___,__X_____,
  _X__X___,__X_____,
  ________,__X_____,
  ________,__X_____,
  ________,__X_____,
  ________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_53F7[ 32] = { /* code 53F7 */
  ________,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  ____X___,________,
  ___X____,________,
  ___XXXXX,XXXX____,
  ________,___X____,
  ________,___X____,
  ________,___X____,
  ________,X_X_____,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_56ED[ 32] = { /* code 56ED */
  ________,________,
  _XXXXXXX,XXXXXX__,
  _X______,_____X__,
  _X__XXXX,XXX__X__,
  _X______,_____X__,
  _X______,_____X__,
  _X_XXXXX,XXXX_X__,
  _X___X__,X____X__,
  _X___X__,X____X__,
  _X___X__,X____X__,
  _X__X___,X__X_X__,
  _X__X___,X__X_X__,
  _X_X____,_XXX_X__,
  _X______,_____X__,
  _XXXXXXX,XXXXXX__,
  _X______,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_5730[ 32] = { /* code 5730 */
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X___X,__X_____,
  ___X___X,__X_XX__,
  XXXXXX_X,__XX_X__,
  ___X___X,_XX__X__,
  ___X__XX,X_X__X__,
  ___X___X,__X__X__,
  ___X___X,__XX_X__,
  ___X___X,__X_X___,
  ___XXX_X,__X___X_,
  XXX____X,__X___X_,
  _X_____X,______X_,
  ________,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_5740[ 32] = { /* code 5740 */
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X___X,__X_____,
  ___X___X,__X_____,
  XXXXXX_X,__X_____,
  ___X___X,__XXXX__,
  ___X___X,__X_____,
  ___X___X,__X_____,
  ___X___X,__X_____,
  ___X___X,__X_____,
  ___XXX_X,__X_____,
  XXX____X,__X_____,
  _X_____X,__X_____,
  _____XXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_5B89[ 32] = { /* code 5B89 */
  ______X_,________,
  _______X,________,
  __XXXXXX,XXXXXX__,
  __X_____,_____X__,
  _X____X_,____X___,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXXXX_,
  _____X__,__X_____,
  ____X___,__X_____,
  ___XX___,_X______,
  _____XX_,_X______,
  _______X,X_______,
  ______X_,_XX_____,
  ____XX__,___X____,
  _XXX____,____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_5BB6[ 32] = { /* code 5BB6 */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X_______,_____X__,
  _XXXXXXX,XXXXXX__,
  ______X_,________,
  ____XX_X,____X___,
  _XXX___X,X__X____,
  ______X_,X_X_____,
  ____XX__,XX______,
  _XXX___X,X_X_____,
  _____XX_,X__XX___,
  ___XX___,X____XX_,
  XXX___X_,X_______,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_5EA7[ 32] = { /* code 5EA7 */
  _______X,________,
  ________,X_______,
  __XXXXXX,XXXXXXX_,
  __X_____,X_______,
  __X__X__,X__X____,
  __X__X__,X__X____,
  __X__X__,X__X____,
  __X_X_X_,X_X_X___,
  __XX___X,XX___X__,
  __X_____,X_______,
  __X_XXXX,XXXXX___,
  __X_____,X_______,
  _X______,X_______,
  _X______,X_______,
  X_XXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_73AF[ 32] = { /* code 73AF */
  ________,________,
  ________,________,
  XXXXXX_X,XXXXXXX_,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,__X_____,
  ___X____,__X_____,
  _XXXXX__,_XX_X___,
  ___X____,X_X__X__,
  ___X___X,__X___X_,
  ___X__X_,__X___X_,
  ___X____,__X_____,
  ___XXX__,__X_____,
  XXX_____,__X_____,
  _X______,__X_____,
  ________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_7535[ 32] = { /* code 7535 */
  _______X,________,
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X_X_,
  _______X,______X_,
  _______X,______X_,
  ________,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_897F[ 32] = { /* code 897F */
  ________,________,
  XXXXXXXX,XXXXXXX_,
  _____X__,_X______,
  _____X__,_X______,
  _____X__,_X______,
  __XXXXXX,XXXXX___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X_X___,__XXX___,
  __XX____,____X___,
  __X_____,____X___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_8BDD[ 32] = { /* code 8BDD */
  ________,____X___,
  __X_____,__XXXX__,
  ___X___X,XXX_____,
  ___X____,__X_____,
  ________,__X_____,
  ______XX,XXXXXXX_,
  XXXX____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X___X,XXXXXX__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  ___X_X_X,_____X__,
  ___XX__X,_____X__,
  ___X___X,XXXXXX__,
  _______X,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_8DEF[ 32] = { /* code 8DEF */
  ________,_X______,
  _XXXXX__,_X______,
  _X___X__,_XXXX___,
  _X___X__,X___X___,
  _X___X_X,_X_X____,
  _XXXXX__,__X_____,
  ___X____,_X_X____,
  ___X____,X___X___,
  ___X___X,_____XX_,
  _X_XXX__,XXXXX___,
  _X_X____,X___X___,
  _X_X____,X___X___,
  _X_X____,X___X___,
  _X_XXX__,X___X___,
  XXX_____,XXXXX___,
  ________,X___X___};

GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_91D1[ 32] = { /* code 91D1 */
  _______X,________,
  _______X,________,
  ______X_,X_______,
  _____X__,_X______,
  ____X___,__X_____,
  ___X____,___X____,
  __X_XXXX,XXX_X___,
  XX_____X,_____XX_,
  _______X,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  ___X___X,___X____,
  ____X__X,___X____,
  ____X__X,__X_____,
  XXXXXXXX,XXXXXXX_,
  ________,________};

/* Start of unicode area <Halfwidth and Fullwidth Forms> */
GUI_CONST_STORAGE unsigned char acGUI_Fonttndz_FF1A[ 32] = { /* code FF1A, FULLWIDTH COLON */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XX____,________,
  __XX____,________,
  ________,________,
  __XX____,________,
  __XX____,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fonttndz_CharInfo[24] = {
   {   8,   8,  1, acGUI_Fonttndz_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_Fonttndz_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_Fonttndz_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_Fonttndz_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_Fonttndz_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_Fonttndz_0039 } /* code 0039 */
  ,{   8,   8,  1, acGUI_Fonttndz_0044 } /* code 0044 */
  ,{  16,  16,  2, acGUI_Fonttndz_4E8C } /* code 4E8C */
  ,{  16,  16,  2, acGUI_Fonttndz_5357 } /* code 5357 */
  ,{  16,  16,  2, acGUI_Fonttndz_53F6 } /* code 53F6 */
  ,{  16,  16,  2, acGUI_Fonttndz_53F7 } /* code 53F7 */
  ,{  16,  16,  2, acGUI_Fonttndz_56ED } /* code 56ED */
  ,{  16,  16,  2, acGUI_Fonttndz_5730 } /* code 5730 */
  ,{  16,  16,  2, acGUI_Fonttndz_5740 } /* code 5740 */
  ,{  16,  16,  2, acGUI_Fonttndz_5B89 } /* code 5B89 */
  ,{  16,  16,  2, acGUI_Fonttndz_5BB6 } /* code 5BB6 */
  ,{  16,  16,  2, acGUI_Fonttndz_5EA7 } /* code 5EA7 */
  ,{  16,  16,  2, acGUI_Fonttndz_73AF } /* code 73AF */
  ,{  16,  16,  2, acGUI_Fonttndz_7535 } /* code 7535 */
  ,{  16,  16,  2, acGUI_Fonttndz_897F } /* code 897F */
  ,{  16,  16,  2, acGUI_Fonttndz_8BDD } /* code 8BDD */
  ,{  16,  16,  2, acGUI_Fonttndz_8DEF } /* code 8DEF */
  ,{  16,  16,  2, acGUI_Fonttndz_91D1 } /* code 91D1 */
  ,{  16,  16,  2, acGUI_Fonttndz_FF1A } /* code FF1A */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop19 = {
   0xFF1A /* first character */
  ,0xFF1A /* last character  */
  ,&GUI_Fonttndz_CharInfo[ 23] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop18 = {
   0x91D1 /* first character */
  ,0x91D1 /* last character  */
  ,&GUI_Fonttndz_CharInfo[ 22] /* address of first character */
  ,&GUI_Fonttndz_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop17 = {
   0x8DEF /* first character */
  ,0x8DEF /* last character  */
  ,&GUI_Fonttndz_CharInfo[ 21] /* address of first character */
  ,&GUI_Fonttndz_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop16 = {
   0x8BDD /* first character */
  ,0x8BDD /* last character  */
  ,&GUI_Fonttndz_CharInfo[ 20] /* address of first character */
  ,&GUI_Fonttndz_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop15 = {
   0x897F /* first character */
  ,0x897F /* last character  */
  ,&GUI_Fonttndz_CharInfo[ 19] /* address of first character */
  ,&GUI_Fonttndz_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop14 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_Fonttndz_CharInfo[ 18] /* address of first character */
  ,&GUI_Fonttndz_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop13 = {
   0x73AF /* first character */
  ,0x73AF /* last character  */
  ,&GUI_Fonttndz_CharInfo[ 17] /* address of first character */
  ,&GUI_Fonttndz_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop12 = {
   0x5EA7 /* first character */
  ,0x5EA7 /* last character  */
  ,&GUI_Fonttndz_CharInfo[ 16] /* address of first character */
  ,&GUI_Fonttndz_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop11 = {
   0x5BB6 /* first character */
  ,0x5BB6 /* last character  */
  ,&GUI_Fonttndz_CharInfo[ 15] /* address of first character */
  ,&GUI_Fonttndz_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop10 = {
   0x5B89 /* first character */
  ,0x5B89 /* last character  */
  ,&GUI_Fonttndz_CharInfo[ 14] /* address of first character */
  ,&GUI_Fonttndz_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop9 = {
   0x5740 /* first character */
  ,0x5740 /* last character  */
  ,&GUI_Fonttndz_CharInfo[ 13] /* address of first character */
  ,&GUI_Fonttndz_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop8 = {
   0x5730 /* first character */
  ,0x5730 /* last character  */
  ,&GUI_Fonttndz_CharInfo[ 12] /* address of first character */
  ,&GUI_Fonttndz_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop7 = {
   0x56ED /* first character */
  ,0x56ED /* last character  */
  ,&GUI_Fonttndz_CharInfo[ 11] /* address of first character */
  ,&GUI_Fonttndz_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop6 = {
   0x53F6 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_Fonttndz_CharInfo[  9] /* address of first character */
  ,&GUI_Fonttndz_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop5 = {
   0x5357 /* first character */
  ,0x5357 /* last character  */
  ,&GUI_Fonttndz_CharInfo[  8] /* address of first character */
  ,&GUI_Fonttndz_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop4 = {
   0x4E8C /* first character */
  ,0x4E8C /* last character  */
  ,&GUI_Fonttndz_CharInfo[  7] /* address of first character */
  ,&GUI_Fonttndz_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop3 = {
   0x0044 /* first character */
  ,0x0044 /* last character  */
  ,&GUI_Fonttndz_CharInfo[  6] /* address of first character */
  ,&GUI_Fonttndz_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop2 = {
   0x0038 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_Fonttndz_CharInfo[  4] /* address of first character */
  ,&GUI_Fonttndz_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttndz_Prop1 = {
   0x0030 /* first character */
  ,0x0033 /* last character  */
  ,&GUI_Fonttndz_CharInfo[  0] /* address of first character */
  ,&GUI_Fonttndz_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fonttndz = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fonttndz_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

